// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GuiVSIXProject
{
    internal sealed partial class Vsix
    {
        public const string Id = "GuiVSIXProject.9c91feb2-c30b-4906-b5ad-9e06585303b9";
        public const string Name = "GuiVSIXProject";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "ru-RU";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
