// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GuiVSIXProject
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GuiVSIXProjectString = "84771605-4e3c-4469-894a-ff601321ae96";
        public static Guid GuiVSIXProject = new Guid(GuiVSIXProjectString);

        public const string GuiVSIXProjectCmdSetString = "12312333-4e3c-4469-894a-ff601321ae96";
        public static Guid GuiVSIXProjectCmdSet = new Guid(GuiVSIXProjectCmdSetString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommand = 0x0100;
        public const int MyMenyGroup = 0x0100;
    }
}
